// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_series_state.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSeriesState = `-- name: GetSeriesState :one
SELECT
    source,
    metric_name,
    env,
    region,
    last_ts,
    last_value,
    baseline,
    mad,
    threshold,
    window_size,
    threshold_k,
    detector,
    producer,
    trace_id,
    updated_at
FROM series_state
WHERE source = $1 AND metric_name = $2 AND env = $3 AND region = $4
`

type GetSeriesStateParams struct {
	Source     string `json:"source"`
	MetricName string `json:"metric_name"`
	Env        string `json:"env"`
	Region     string `json:"region"`
}

type GetSeriesStateRow struct {
	Source     string             `json:"source"`
	MetricName string             `json:"metric_name"`
	Env        string             `json:"env"`
	Region     string             `json:"region"`
	LastTs     int64              `json:"last_ts"`
	LastValue  float64            `json:"last_value"`
	Baseline   float64            `json:"baseline"`
	Mad        float64            `json:"mad"`
	Threshold  float64            `json:"threshold"`
	WindowSize int32              `json:"window_size"`
	ThresholdK float64            `json:"threshold_k"`
	Detector   string             `json:"detector"`
	Producer   string             `json:"producer"`
	TraceID    string             `json:"trace_id"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSeriesState(ctx context.Context, arg GetSeriesStateParams) (GetSeriesStateRow, error) {
	row := q.db.QueryRow(ctx, getSeriesState,
		arg.Source,
		arg.MetricName,
		arg.Env,
		arg.Region,
	)
	var i GetSeriesStateRow
	err := row.Scan(
		&i.Source,
		&i.MetricName,
		&i.Env,
		&i.Region,
		&i.LastTs,
		&i.LastValue,
		&i.Baseline,
		&i.Mad,
		&i.Threshold,
		&i.WindowSize,
		&i.ThresholdK,
		&i.Detector,
		&i.Producer,
		&i.TraceID,
		&i.UpdatedAt,
	)
	return i, err
}
