// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_anomaly_event.sql

package db

import (
	"context"
)

const insertAnomalyEvent = `-- name: InsertAnomalyEvent :exec
INSERT INTO anomaly_events (
    source, metric_name, env, region, instance_id,
    ts, value, baseline, mad, threshold,
    window_size, threshold_k, detector, producer,
    trace_id, event_id, event_type, event_version,
    occurred_at, produced_at
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
             $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
         )
`

type InsertAnomalyEventParams struct {
	Source       string  `json:"source"`
	MetricName   string  `json:"metric_name"`
	Env          string  `json:"env"`
	Region       string  `json:"region"`
	InstanceID   string  `json:"instance_id"`
	Ts           int64   `json:"ts"`
	Value        float64 `json:"value"`
	Baseline     float64 `json:"baseline"`
	Mad          float64 `json:"mad"`
	Threshold    float64 `json:"threshold"`
	WindowSize   int32   `json:"window_size"`
	ThresholdK   float64 `json:"threshold_k"`
	Detector     string  `json:"detector"`
	Producer     string  `json:"producer"`
	TraceID      string  `json:"trace_id"`
	EventID      string  `json:"event_id"`
	EventType    string  `json:"event_type"`
	EventVersion int32   `json:"event_version"`
	OccurredAt   string  `json:"occurred_at"`
	ProducedAt   string  `json:"produced_at"`
}

func (q *Queries) InsertAnomalyEvent(ctx context.Context, arg InsertAnomalyEventParams) error {
	_, err := q.db.Exec(ctx, insertAnomalyEvent,
		arg.Source,
		arg.MetricName,
		arg.Env,
		arg.Region,
		arg.InstanceID,
		arg.Ts,
		arg.Value,
		arg.Baseline,
		arg.Mad,
		arg.Threshold,
		arg.WindowSize,
		arg.ThresholdK,
		arg.Detector,
		arg.Producer,
		arg.TraceID,
		arg.EventID,
		arg.EventType,
		arg.EventVersion,
		arg.OccurredAt,
		arg.ProducedAt,
	)
	return err
}
