// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_series.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSeries = `-- name: ListSeries :many
SELECT
    source,
    metric_name,
    env,
    region,
    last_ts,
    last_value,
    baseline,
    mad,
    threshold,
    window_size,
    threshold_k,
    detector,
    producer,
    trace_id,
    updated_at
FROM series_state
WHERE
    ($1::text IS NULL OR source = $1) AND
    ($2::text IS NULL OR metric_name = $2) AND
    ($3::text IS NULL OR env = $3) AND
    ($4::text IS NULL OR region = $4)
ORDER BY updated_at DESC
    LIMIT $5
`

type ListSeriesParams struct {
	Source     pgtype.Text `json:"source"`
	MetricName pgtype.Text `json:"metric_name"`
	Env        pgtype.Text `json:"env"`
	Region     pgtype.Text `json:"region"`
	LimitVal   int32       `json:"limit_val"`
}

type ListSeriesRow struct {
	Source     string             `json:"source"`
	MetricName string             `json:"metric_name"`
	Env        string             `json:"env"`
	Region     string             `json:"region"`
	LastTs     int64              `json:"last_ts"`
	LastValue  float64            `json:"last_value"`
	Baseline   float64            `json:"baseline"`
	Mad        float64            `json:"mad"`
	Threshold  float64            `json:"threshold"`
	WindowSize int32              `json:"window_size"`
	ThresholdK float64            `json:"threshold_k"`
	Detector   string             `json:"detector"`
	Producer   string             `json:"producer"`
	TraceID    string             `json:"trace_id"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSeries(ctx context.Context, arg ListSeriesParams) ([]ListSeriesRow, error) {
	rows, err := q.db.Query(ctx, listSeries,
		arg.Source,
		arg.MetricName,
		arg.Env,
		arg.Region,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeriesRow
	for rows.Next() {
		var i ListSeriesRow
		if err := rows.Scan(
			&i.Source,
			&i.MetricName,
			&i.Env,
			&i.Region,
			&i.LastTs,
			&i.LastValue,
			&i.Baseline,
			&i.Mad,
			&i.Threshold,
			&i.WindowSize,
			&i.ThresholdK,
			&i.Detector,
			&i.Producer,
			&i.TraceID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
