// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_anomalies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAnomalies = `-- name: ListAnomalies :many
SELECT
    id,
    source,
    metric_name,
    env,
    region,
    instance_id,
    ts,
    value,
    baseline,
    mad,
    threshold,
    window_size,
    threshold_k,
    detector,
    producer,
    trace_id,
    event_id,
    created_at
FROM anomaly_events
WHERE
    ($1::bigint IS NULL OR ts >= $1) AND
    ($2::bigint IS NULL OR ts <= $2) AND
    ($3::text IS NULL OR source = $3) AND
    ($4::text IS NULL OR metric_name = $4) AND
    ($5::text IS NULL OR env = $5) AND
    ($6::text IS NULL OR region = $6) AND
    ($7::text IS NULL OR instance_id = $7)
ORDER BY ts DESC
    LIMIT $9 OFFSET $8
`

type ListAnomaliesParams struct {
	FromTs     pgtype.Int8 `json:"from_ts"`
	ToTs       pgtype.Int8 `json:"to_ts"`
	Source     pgtype.Text `json:"source"`
	MetricName pgtype.Text `json:"metric_name"`
	Env        pgtype.Text `json:"env"`
	Region     pgtype.Text `json:"region"`
	InstanceID pgtype.Text `json:"instance_id"`
	Offset     int32       `json:"offset"`
	Limit      int32       `json:"limit"`
}

type ListAnomaliesRow struct {
	ID         int64              `json:"id"`
	Source     string             `json:"source"`
	MetricName string             `json:"metric_name"`
	Env        string             `json:"env"`
	Region     string             `json:"region"`
	InstanceID string             `json:"instance_id"`
	Ts         int64              `json:"ts"`
	Value      float64            `json:"value"`
	Baseline   float64            `json:"baseline"`
	Mad        float64            `json:"mad"`
	Threshold  float64            `json:"threshold"`
	WindowSize int32              `json:"window_size"`
	ThresholdK float64            `json:"threshold_k"`
	Detector   string             `json:"detector"`
	Producer   string             `json:"producer"`
	TraceID    string             `json:"trace_id"`
	EventID    string             `json:"event_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAnomalies(ctx context.Context, arg ListAnomaliesParams) ([]ListAnomaliesRow, error) {
	rows, err := q.db.Query(ctx, listAnomalies,
		arg.FromTs,
		arg.ToTs,
		arg.Source,
		arg.MetricName,
		arg.Env,
		arg.Region,
		arg.InstanceID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnomaliesRow
	for rows.Next() {
		var i ListAnomaliesRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.MetricName,
			&i.Env,
			&i.Region,
			&i.InstanceID,
			&i.Ts,
			&i.Value,
			&i.Baseline,
			&i.Mad,
			&i.Threshold,
			&i.WindowSize,
			&i.ThresholdK,
			&i.Detector,
			&i.Producer,
			&i.TraceID,
			&i.EventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
