// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnomalyEvent struct {
	ID           int64              `json:"id"`
	Source       string             `json:"source"`
	MetricName   string             `json:"metric_name"`
	Env          string             `json:"env"`
	Region       string             `json:"region"`
	InstanceID   string             `json:"instance_id"`
	Ts           int64              `json:"ts"`
	Value        float64            `json:"value"`
	Baseline     float64            `json:"baseline"`
	Mad          float64            `json:"mad"`
	Threshold    float64            `json:"threshold"`
	WindowSize   int32              `json:"window_size"`
	ThresholdK   float64            `json:"threshold_k"`
	Detector     string             `json:"detector"`
	Producer     string             `json:"producer"`
	TraceID      string             `json:"trace_id"`
	EventID      string             `json:"event_id"`
	EventType    string             `json:"event_type"`
	EventVersion int32              `json:"event_version"`
	OccurredAt   string             `json:"occurred_at"`
	ProducedAt   string             `json:"produced_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ProcessedEvent struct {
	DedupKey    string             `json:"dedup_key"`
	Subject     string             `json:"subject"`
	StreamSeq   int64              `json:"stream_seq"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type SeriesState struct {
	Source       string             `json:"source"`
	MetricName   string             `json:"metric_name"`
	Env          string             `json:"env"`
	Region       string             `json:"region"`
	LastTs       int64              `json:"last_ts"`
	LastValue    float64            `json:"last_value"`
	Baseline     float64            `json:"baseline"`
	Mad          float64            `json:"mad"`
	Threshold    float64            `json:"threshold"`
	WindowSize   int32              `json:"window_size"`
	ThresholdK   float64            `json:"threshold_k"`
	Detector     string             `json:"detector"`
	Producer     string             `json:"producer"`
	TraceID      string             `json:"trace_id"`
	EventID      string             `json:"event_id"`
	EventVersion int32              `json:"event_version"`
	OccurredAt   string             `json:"occurred_at"`
	ProducedAt   string             `json:"produced_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
