// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: try_mark_processed.sql

package db

import (
	"context"
)

const tryMarkProcessed = `-- name: TryMarkProcessed :one
INSERT INTO processed_events (dedup_key, subject, stream_seq)
VALUES ($1, $2, $3)
    ON CONFLICT (dedup_key) DO NOTHING
RETURNING dedup_key
`

type TryMarkProcessedParams struct {
	DedupKey  string `json:"dedup_key"`
	Subject   string `json:"subject"`
	StreamSeq int64  `json:"stream_seq"`
}

func (q *Queries) TryMarkProcessed(ctx context.Context, arg TryMarkProcessedParams) (string, error) {
	row := q.db.QueryRow(ctx, tryMarkProcessed, arg.DedupKey, arg.Subject, arg.StreamSeq)
	var dedup_key string
	err := row.Scan(&dedup_key)
	return dedup_key, err
}
