// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upsert_series_state.sql

package db

import (
	"context"
)

const upsertSeriesState = `-- name: UpsertSeriesState :exec
INSERT INTO series_state (
    source, metric_name, env, region,
    last_ts, last_value,
    baseline, mad, threshold,
    window_size, threshold_k, detector,
    producer, trace_id,
    event_id, event_version, occurred_at, produced_at
) VALUES (
             $1,$2,$3,$4,
             $5,$6,
             $7,$8,$9,
             $10,$11,$12,
             $13,$14,
             $15,$16,$17,$18
         )
    ON CONFLICT (source, metric_name, env, region)
DO UPDATE SET
    last_ts = EXCLUDED.last_ts,
           last_value = EXCLUDED.last_value,
           baseline = EXCLUDED.baseline,
           mad = EXCLUDED.mad,
           threshold = EXCLUDED.threshold,
           window_size = EXCLUDED.window_size,
           threshold_k = EXCLUDED.threshold_k,
           detector = EXCLUDED.detector,
           producer = EXCLUDED.producer,
           trace_id = EXCLUDED.trace_id,
           event_id = EXCLUDED.event_id,
           event_version = EXCLUDED.event_version,
           occurred_at = EXCLUDED.occurred_at,
           produced_at = EXCLUDED.produced_at,
           updated_at = now()
`

type UpsertSeriesStateParams struct {
	Source       string  `json:"source"`
	MetricName   string  `json:"metric_name"`
	Env          string  `json:"env"`
	Region       string  `json:"region"`
	LastTs       int64   `json:"last_ts"`
	LastValue    float64 `json:"last_value"`
	Baseline     float64 `json:"baseline"`
	Mad          float64 `json:"mad"`
	Threshold    float64 `json:"threshold"`
	WindowSize   int32   `json:"window_size"`
	ThresholdK   float64 `json:"threshold_k"`
	Detector     string  `json:"detector"`
	Producer     string  `json:"producer"`
	TraceID      string  `json:"trace_id"`
	EventID      string  `json:"event_id"`
	EventVersion int32   `json:"event_version"`
	OccurredAt   string  `json:"occurred_at"`
	ProducedAt   string  `json:"produced_at"`
}

func (q *Queries) UpsertSeriesState(ctx context.Context, arg UpsertSeriesStateParams) error {
	_, err := q.db.Exec(ctx, upsertSeriesState,
		arg.Source,
		arg.MetricName,
		arg.Env,
		arg.Region,
		arg.LastTs,
		arg.LastValue,
		arg.Baseline,
		arg.Mad,
		arg.Threshold,
		arg.WindowSize,
		arg.ThresholdK,
		arg.Detector,
		arg.Producer,
		arg.TraceID,
		arg.EventID,
		arg.EventVersion,
		arg.OccurredAt,
		arg.ProducedAt,
	)
	return err
}
